apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hybrid-app
  template:
    metadata:
      labels:
        app: hybrid-app
    spec:
      containers:
        - name: hybrid-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80